### ISSUE TITLE
提几个建议

### ISSUE THREAD

**Issue by gqbre** [songsiqi/px2rem-gulp#2]
1. 生成的css 为何都是加 *.debug.css，是否考虑加个选项禁用自动加 .debug 的功能？
2. 生成的CSS 格式是否考虑添加规范化格式的功能？如 expanded ，compact 等？
谢谢作者的付出。

**Comment by songsiqi** [comment]
@gqbre 这是一个很老的插件，在 gulp 环境下也可以使用 `postcss-px2rem`，自己定义生成文件名更方便
